export const DISPATCH_EVENT_TYPES = {
  MATCHING_STARTED: 'MATCHING_STARTED',
  CANDIDATES_SEARCHED: 'CANDIDATES_SEARCHED',
  OFFER_SENT: 'OFFER_SENT',
  OFFER_EXPIRED: 'OFFER_EXPIRED',
  OFFER_DECLINED: 'OFFER_DECLINED',
  OFFER_ACCEPTED: 'OFFER_ACCEPTED',
  TIER_ESCALATED: 'TIER_ESCALATED',
  MATCH_EXHAUSTED: 'MATCH_EXHAUSTED',
  BEAUTICIAN_ONLINE_RETRIGGER: 'BEAUTICIAN_ONLINE_RETRIGGER',
  EXHAUSTED_WAKE_RETRY: 'EXHAUSTED_WAKE_RETRY',
  MANUAL_RETRY: 'MANUAL_RETRY',
  FORCE_ASSIGNED: 'FORCE_ASSIGNED',
  REASSIGNED: 'REASSIGNED',
  DISPATCH_CANCELLED: 'DISPATCH_CANCELLED',
} as const;

export type DispatchEventType =
  (typeof DISPATCH_EVENT_TYPES)[keyof typeof DISPATCH_EVENT_TYPES];