-- ============================================================================
-- Hairlux additive-only migration — Recruitment, Attendance, Leave, Inventory modules
-- Generated by hand (not via `prisma migrate dev`) specifically to avoid
-- touching the pre-existing constraint/index drift on unrelated tables.
--
-- Safe to run as-is via psql. Every statement is either:
--   - CREATE TYPE (new enum, no conflict possible)
--   - CREATE TABLE IF NOT EXISTS (new table only)
--   - ALTER TABLE ... ADD COLUMN IF NOT EXISTS (additive, nullable/defaulted)
-- Nothing here drops, renames, or alters an existing column, constraint,
-- or index on any table. BACK UP FIRST regardless (you already have).
-- ============================================================================

BEGIN;

-- ── New enum types ──────────────────────────────────────────────────────────

DO $$ BEGIN
  CREATE TYPE "JobPostingStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'CLOSED', 'ARCHIVED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "InterviewOutcome" AS ENUM ('PASS', 'FAIL', 'HOLD');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "OfferLetterStatus" AS ENUM ('SENT', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'WITHDRAWN');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "AttendanceStatus" AS ENUM ('PRESENT', 'LATE', 'ABSENT', 'ON_LEAVE', 'APPROVED_PERMISSION', 'PUBLIC_HOLIDAY');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "LeaveRequestType" AS ENUM ('ANNUAL_LEAVE', 'SICK_LEAVE', 'CASUAL_LEAVE', 'DAY_OFF', 'PERMISSION_LATE_ARRIVAL', 'PERMISSION_EARLY_DEPARTURE', 'OVERTIME_REQUEST');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "LeaveRequestStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- ── staff_locations: GPS + grace period fields ──────────────────────────────

ALTER TABLE "staff_locations"
  ADD COLUMN IF NOT EXISTS "gps_lat" DECIMAL(10,7),
  ADD COLUMN IF NOT EXISTS "gps_lng" DECIMAL(10,7),
  ADD COLUMN IF NOT EXISTS "approved_radius_meters" INTEGER,
  ADD COLUMN IF NOT EXISTS "late_grace_period_minutes" INTEGER NOT NULL DEFAULT 10;


-- ── staff: per-staff grace period override ──────────────────────────────────

ALTER TABLE "staff"
  ADD COLUMN IF NOT EXISTS "late_grace_period_override" INTEGER;


-- ── job_postings: branch/department/salary/status lifecycle ────────────────

ALTER TABLE "job_postings"
  ADD COLUMN IF NOT EXISTS "branch_id" TEXT,
  ADD COLUMN IF NOT EXISTS "department" TEXT,
  ADD COLUMN IF NOT EXISTS "status" "JobPostingStatus" NOT NULL DEFAULT 'DRAFT',
  ADD COLUMN IF NOT EXISTS "closed_reason" TEXT,
  ADD COLUMN IF NOT EXISTS "salary_min" DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS "salary_max" DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS "salary_note" TEXT;

DO $$ BEGIN
  ALTER TABLE "job_postings"
    ADD CONSTRAINT "job_postings_branch_id_fkey"
    FOREIGN KEY ("branch_id") REFERENCES "staff_locations"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "job_postings_status_idx" ON "job_postings"("status");
CREATE INDEX IF NOT EXISTS "job_postings_branch_id_idx" ON "job_postings"("branch_id");


-- ── application: job FK, interview outcome, gate relations ─────────────────

ALTER TABLE "Application"
  ADD COLUMN IF NOT EXISTS "job_id" TEXT,
  ADD COLUMN IF NOT EXISTS "interviewOutcome" "InterviewOutcome",
  ADD COLUMN IF NOT EXISTS "interviewerId" TEXT;

DO $$ BEGIN
  ALTER TABLE "Application"
    ADD CONSTRAINT "Application_job_id_fkey"
    FOREIGN KEY ("job_id") REFERENCES "job_postings"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "Application"
    ADD CONSTRAINT "Application_interviewerId_fkey"
    FOREIGN KEY ("interviewerId") REFERENCES "staff"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- ── employment_approvals (new table) ────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "employment_approvals" (
  "id" TEXT NOT NULL,
  "application_id" TEXT NOT NULL,
  "approved_by_id" TEXT NOT NULL,
  "approved_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "notes" TEXT,
  CONSTRAINT "employment_approvals_pkey" PRIMARY KEY ("id")
);

DO $$ BEGIN
  ALTER TABLE "employment_approvals"
    ADD CONSTRAINT "employment_approvals_application_id_key" UNIQUE ("application_id");
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "employment_approvals"
    ADD CONSTRAINT "employment_approvals_application_id_fkey"
    FOREIGN KEY ("application_id") REFERENCES "Application"("id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "employment_approvals"
    ADD CONSTRAINT "employment_approvals_approved_by_id_fkey"
    FOREIGN KEY ("approved_by_id") REFERENCES "users"("id");
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- ── offer_letters (new table) ───────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "offer_letters" (
  "id" TEXT NOT NULL,
  "application_id" TEXT NOT NULL,
  "job_posting_id" TEXT,
  "role" TEXT NOT NULL,
  "branch_id" TEXT,
  "base_salary" DECIMAL(10,2) NOT NULL,
  "allowances" DECIMAL(10,2),
  "compensation_note" TEXT,
  "effective_date" TIMESTAMP(3) NOT NULL,
  "template_used" TEXT,
  "status" "OfferLetterStatus" NOT NULL DEFAULT 'SENT',
  "generated_by_id" TEXT NOT NULL,
  "generated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "sent_at" TIMESTAMP(3),
  "responded_at" TIMESTAMP(3),
  "decline_reason" TEXT,
  CONSTRAINT "offer_letters_pkey" PRIMARY KEY ("id")
);

DO $$ BEGIN
  ALTER TABLE "offer_letters"
    ADD CONSTRAINT "offer_letters_application_id_key" UNIQUE ("application_id");
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "offer_letters"
    ADD CONSTRAINT "offer_letters_application_id_fkey"
    FOREIGN KEY ("application_id") REFERENCES "Application"("id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "offer_letters"
    ADD CONSTRAINT "offer_letters_job_posting_id_fkey"
    FOREIGN KEY ("job_posting_id") REFERENCES "job_postings"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "offer_letters"
    ADD CONSTRAINT "offer_letters_branch_id_fkey"
    FOREIGN KEY ("branch_id") REFERENCES "staff_locations"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "offer_letters"
    ADD CONSTRAINT "offer_letters_generated_by_id_fkey"
    FOREIGN KEY ("generated_by_id") REFERENCES "users"("id");
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "offer_letters_status_idx" ON "offer_letters"("status");


-- ── attendance_records: GPS, status, late/overtime, manual correction ──────

ALTER TABLE "attendance_records"
  ADD COLUMN IF NOT EXISTS "check_in_lat" DECIMAL(10,7),
  ADD COLUMN IF NOT EXISTS "check_in_lng" DECIMAL(10,7),
  ADD COLUMN IF NOT EXISTS "check_out_lat" DECIMAL(10,7),
  ADD COLUMN IF NOT EXISTS "check_out_lng" DECIMAL(10,7),
  ADD COLUMN IF NOT EXISTS "status" "AttendanceStatus" NOT NULL DEFAULT 'PRESENT',
  ADD COLUMN IF NOT EXISTS "late_minutes" INTEGER,
  ADD COLUMN IF NOT EXISTS "overtime_minutes" INTEGER,
  ADD COLUMN IF NOT EXISTS "early_departure_minutes" INTEGER,
  ADD COLUMN IF NOT EXISTS "is_manually_adjusted" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "adjustment_reason" TEXT,
  ADD COLUMN IF NOT EXISTS "adjusted_by_id" TEXT;

DO $$ BEGIN
  ALTER TABLE "attendance_records"
    ADD CONSTRAINT "attendance_records_adjusted_by_id_fkey"
    FOREIGN KEY ("adjusted_by_id") REFERENCES "users"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- ── leave_requests (new table) ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "leave_requests" (
  "id" TEXT NOT NULL,
  "staff_id" TEXT NOT NULL,
  "type" "LeaveRequestType" NOT NULL,
  "start_date" DATE NOT NULL,
  "end_date" DATE NOT NULL,
  "start_time" TEXT,
  "end_time" TEXT,
  "reason" TEXT NOT NULL,
  "status" "LeaveRequestStatus" NOT NULL DEFAULT 'PENDING',
  "approver_id" TEXT,
  "approved_at" TIMESTAMP(3),
  "rejection_reason" TEXT,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "leave_requests_pkey" PRIMARY KEY ("id")
);

DO $$ BEGIN
  ALTER TABLE "leave_requests"
    ADD CONSTRAINT "leave_requests_staff_id_fkey"
    FOREIGN KEY ("staff_id") REFERENCES "staff"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "leave_requests"
    ADD CONSTRAINT "leave_requests_approver_id_fkey"
    FOREIGN KEY ("approver_id") REFERENCES "staff"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "leave_requests_staff_id_status_idx" ON "leave_requests"("staff_id", "status");
CREATE INDEX IF NOT EXISTS "leave_requests_approver_id_status_idx" ON "leave_requests"("approver_id", "status");

-- ── inventory module: categories, stock movements, low-stock alerts, transfers ──

DO $$ BEGIN
  CREATE TYPE "InventoryCategory" AS ENUM ('FOR_SALE', 'INTERNAL_USE', 'STORAGE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "StockMovementType" AS ENUM ('RECEIVED', 'SOLD', 'CONSUMED', 'ADJUSTMENT', 'TRANSFER_OUT', 'TRANSFER_IN');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "StockTransferStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "LowStockAlertStage" AS ENUM ('SUPERVISOR', 'OPERATIONS', 'MANAGEMENT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "inventory_items" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "category" "InventoryCategory" NOT NULL,
  "branch_id" TEXT NOT NULL,
  "unit" TEXT,
  "current_quantity" INTEGER NOT NULL DEFAULT 0,
  "low_stock_threshold" INTEGER NOT NULL DEFAULT 5,
  "expiry_date" DATE,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "inventory_items_pkey" PRIMARY KEY ("id")
);

DO $$ BEGIN
  ALTER TABLE "inventory_items"
    ADD CONSTRAINT "inventory_items_branch_id_name_category_key" UNIQUE ("branch_id", "name", "category");
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "inventory_items"
    ADD CONSTRAINT "inventory_items_branch_id_fkey"
    FOREIGN KEY ("branch_id") REFERENCES "staff_locations"("id");
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "inventory_items_branch_id_category_idx" ON "inventory_items"("branch_id", "category");

CREATE TABLE IF NOT EXISTS "stock_movements" (
  "id" TEXT NOT NULL,
  "item_id" TEXT NOT NULL,
  "type" "StockMovementType" NOT NULL,
  "quantity_delta" INTEGER NOT NULL,
  "reference_id" TEXT,
  "performed_by_id" TEXT NOT NULL,
  "reason" TEXT,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "stock_movements_pkey" PRIMARY KEY ("id")
);

DO $$ BEGIN
  ALTER TABLE "stock_movements"
    ADD CONSTRAINT "stock_movements_item_id_fkey"
    FOREIGN KEY ("item_id") REFERENCES "inventory_items"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "stock_movements"
    ADD CONSTRAINT "stock_movements_performed_by_id_fkey"
    FOREIGN KEY ("performed_by_id") REFERENCES "staff"("id");
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "stock_movements_item_id_created_at_idx" ON "stock_movements"("item_id", "created_at");

CREATE TABLE IF NOT EXISTS "low_stock_alerts" (
  "id" TEXT NOT NULL,
  "item_id" TEXT NOT NULL,
  "triggered_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "current_stage" "LowStockAlertStage" NOT NULL DEFAULT 'SUPERVISOR',
  "escalated_at" TIMESTAMP(3),
  "resolved_at" TIMESTAMP(3),
  "resolved_by_id" TEXT,
  CONSTRAINT "low_stock_alerts_pkey" PRIMARY KEY ("id")
);

DO $$ BEGIN
  ALTER TABLE "low_stock_alerts"
    ADD CONSTRAINT "low_stock_alerts_item_id_fkey"
    FOREIGN KEY ("item_id") REFERENCES "inventory_items"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "low_stock_alerts"
    ADD CONSTRAINT "low_stock_alerts_resolved_by_id_fkey"
    FOREIGN KEY ("resolved_by_id") REFERENCES "staff"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "low_stock_alerts_item_id_resolved_at_idx" ON "low_stock_alerts"("item_id", "resolved_at");

CREATE TABLE IF NOT EXISTS "stock_transfers" (
  "id" TEXT NOT NULL,
  "from_item_id" TEXT NOT NULL,
  "to_branch_id" TEXT NOT NULL,
  "quantity" INTEGER NOT NULL,
  "status" "StockTransferStatus" NOT NULL DEFAULT 'PENDING',
  "requested_by_id" TEXT NOT NULL,
  "approved_by_id" TEXT,
  "approved_at" TIMESTAMP(3),
  "completed_at" TIMESTAMP(3),
  "rejection_reason" TEXT,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "stock_transfers_pkey" PRIMARY KEY ("id")
);

DO $$ BEGIN
  ALTER TABLE "stock_transfers"
    ADD CONSTRAINT "stock_transfers_from_item_id_fkey"
    FOREIGN KEY ("from_item_id") REFERENCES "inventory_items"("id");
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "stock_transfers"
    ADD CONSTRAINT "stock_transfers_to_branch_id_fkey"
    FOREIGN KEY ("to_branch_id") REFERENCES "staff_locations"("id");
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "stock_transfers"
    ADD CONSTRAINT "stock_transfers_requested_by_id_fkey"
    FOREIGN KEY ("requested_by_id") REFERENCES "staff"("id");
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "stock_transfers"
    ADD CONSTRAINT "stock_transfers_approved_by_id_fkey"
    FOREIGN KEY ("approved_by_id") REFERENCES "staff"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

COMMIT;