export { baseTemplate } from './base.template';
export { otpTemplate } from './otp.template';
export { resetPasswordTemplate } from './reset-password.template';
export { bookingConfirmationTemplate } from './booking-confirmation.template';
export { guestBookingNotificationTemplate } from './guest-booking-notification.template';
export { depositSuccessTemplate } from './deposit-success.template';
export { referralRewardTemplate } from './referral-reward.template';
export type { BaseEmailOptions } from './base.template';
export type { BookingConfirmationData } from './booking-confirmation.template';
export type { GuestBookingNotificationData } from './guest-booking-notification.template';
export type { DepositSuccessData } from './deposit-success.template';
export type { ReferralRewardData } from './referral-reward.template';
